---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: alpine
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: alpine
  minReplicas: 2
  maxReplicas: 60
  targetCPUUtilizationPercentage: 50
