# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alpine
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - alpine.dev.itshellws-k8s.com
  rules:
  - host: alpine.dev.itshellws-k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: alpine
          servicePort: 80
