version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201707-01
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker version
      - deploy:
          name: Publish to Docker Hub
          command: |
            mv /home/ubuntu/docker-httpd-fpm/docker-build /home/ubuntu/bin/docker-build
            chmod +x /home/ubuntu/bin/docker-build
            docker-build pull || true
            docker-build build

