version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201707-01
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            docker version

dependencies:
  pre:
    - docker version
    - mv /home/ubuntu/alpine/docker-build /home/ubuntu/bin/docker-build
    - chmod +x /home/ubuntu/bin/docker-build
  override:
    - docker-build pull || true
    - docker-build build

test:
  override:
    - "true"

deployment:
  github_release:
    tag: /v[0-9]+(\.[0-9]+)*/
    commands:
      - docker-build push
      - docker images
  dockerhub_release:
    tag: /a[0-9]+(\.[0-9]+)*/
    commands:
      - docker-build push
      - docker images




