version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install docker-build
          command:
                mv /home/ubuntu/docker-httpd-fpm/docker-build /home/ubuntu/bin/docker-build
                chmod +x /home/ubuntu/bin/docker-build
                docker-build pull || true
                docker-build build
