version: 2
jobs:
  nontest:
    machine: true
    working_directory: /home/circleci/app
    steps:
      - checkout
      - run: echo $CIRCLE_TAG
      - run: docker login -u ${docker_user} -p ${docker_pass}
      - run: docker build -t "vikingo/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG" .
      - run: docker push "vikingo/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG"

workflows:
  version: 2
  build:
    jobs:
      - nontest:
          filters:
            tags:
             only: /v[0-9]+(\.[0-9]+)*/


