version: 2
jobs:
  build:
    working_directory: /home/circleci/app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: 
         echo $CIRCLE_TAG
         docker login -u ${docker_user} -p ${docker_pass}
         docker tag app "vikingo/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG"
         docker push "vikingo/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG"

deployment:
  deploy_docker:
    tag: /v[0-9]+(\.[0-9]+)*/
    commands:
       - docker login -u ${docker_user} -p ${docker_pass}
       - docker tag app "vikingo/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG"
       - docker push "vikingo/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG"
