apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: tn
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginx
        env: stg
        product: tn
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx
        image: vikingo/alpine:v0.0.59
        imagePullPolicy: Always
        env:
        - name: VARIABLE1
          value: "My name is Juan and I'm a variable"
        - name: VARIABLE2
          value: "My name is Lucho and I'm a variable"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30 
          timeoutSeconds: 1
      nodeSelector:
        kops.k8s.io/instancegroup: tn
      imagePullSecrets:
        - name: myregistrykey

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: nginx
    env: stg
    product: tn
  name: nginx
  namespace: tn
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
    env: stg
    product: tn
